### ISSUE TITLE
Leaderboard bug 

### ISSUE THREAD

**Issue by lunadraws** [saiteja-madha/discord-js-bot#110]
invite leaderboard does not show correct top
I think it's the vanity ranking that's the problem 
![IMG_20220302_090130](https://user-images.githubusercontent.com/68550443/156319794-141db9c4-3e91-49bb-b6c2-cecde34589a5.jpg)
![IMG_20220302_081544](https://user-images.githubusercontent.com/68550443/156319796-cf87e4c4-c97a-44b3-a9a0-a24254b32d2d.jpg)

**Comment by saiteja-madha** [comment]
Yes this can be the case.
Will check and add it to the leaderboard as well
