### ISSUE TITLE
Music Cmds

### ISSUE THREAD

**Issue by SpaceLeft** [saiteja-madha/discord-js-bot#117]
Please add more commands in music

**Comment by SpaceLeft** [comment]
@saiteja-madha

**Comment by ghost** [comment]
Hello please specify what commands/the type of commands you want.  They will not be implemented until the v5 release like all other commands requests.

**Comment by SpaceLeft** [comment]
pitch, speed, clearqueue, autoplay, back, jump, replay, seek, rewind, system dj

**Comment by SpaceLeft** [comment]
filters 
8d, bassboost, distorsion, filters, karaoke, lowpass, nightcore, resetfilters, rotation, tremolo, vibrato
