### ISSUE TITLE
GIVEAWAY cmd and rep cmd has bug

### ISSUE THREAD

**Issue by Aditya9062** [saiteja-madha/discord-js-bot#119]
after giving rep its showing opps error occured but the user got rep 
and in giveaway start cmd entering duration in minutes still its showing duration not sprcified

please fix it and in giveaway start cmd add duration in hour and minutes both

**Comment by saiteja-madha** [comment]
Any logs or attachments that can help us investigate?
Feel free to join us at: https://discord.gg/fE75UShbqB

**Comment by saiteja-madha** [comment]
Rep command seems to work.
Can you please elaborate on how we can replicate the error?
