### ISSUE TITLE
Dashboard help

### ISSUE THREAD

**Issue by Cxmplement** [saiteja-madha/discord-js-bot#124]
**Dashboard Bug**
The page for localhost:8080 brings up the discord bot Auth, but after doing so it redirects back to it.

**To Reproduce**
Steps to reproduce the behavior: I really don't know

**Expected behavior**

I expected it to bring up the dashboard

**Screenshots**
![image](https://user-images.githubusercontent.com/73006302/163728771-231ad55a-b9bc-432c-8e1e-0a18df676ff6.png)

**If possible**
 - NodeJS version: 16.14.0
 - Bot version: Latest Version

**Additional context**

**Comment by InvincibleTheDev** [comment]
Could you please join our discord server and show me your config files. You may have your redirect url mixed up but I need more info.

**Comment by saiteja-madha** [comment]
Currently the error messages are not logged for dashboard auth errors

**Comment by Nostorian** [comment]
> not logged for dashboard auth errors

update the server link, the current one is outdated
