### ISSUE TITLE
next update

### ISSUE THREAD

**Issue by Aditya9062** [saiteja-madha/discord-js-bot#126]
1.  Fix giveaway start cmd bug 
2.  in ban , kick, warn cmd make like that the bot dm the user why they got ban . kick , warn 
3. add membercount , snipe , afk command
4. also remove yt from music system add other platform like soundcloud cause its again discord tos.

![IMG_20220421_230729](https://user-images.githubusercontent.com/95363688/165038202-6151de97-0168-49c5-9859-40accc6e4710.jpg)

**Comment by saiteja-madha** [comment]
This bug is verified.
This PR (https://github.com/saiteja-madha/discord-js-bot/pull/128) resolves this issue

**Comment by Adityarust** [comment]
Giveaway bug fixed or not?
