### ISSUE TITLE
Small typo in flag translation 

### ISSUE THREAD

**Issue by Darshyadav1** [saiteja-madha/discord-js-bot#127]
**Describe the bug**
There's a typo in flag translation where if you react with indian flag it shows the spelling of "Punjabi" wrong 

**Expected behavior**
Spelling should be "Punjabi" instead of "panjabi"

**Screenshots**

![Screenshot_20220425-215226_Discord.jpg](https://user-images.githubusercontent.com/92047876/165131611-e7a7880d-75ed-4b6f-8f08-0d7242bec26d.jpg)

**Comment by ghost** [comment]
fixed bug in v5 pre-release 

![image](https://user-images.githubusercontent.com/84764855/170901617-39c5a1d8-d914-4526-992e-c840bfd8bac0.png)
