### ISSUE TITLE
feature

### ISSUE THREAD

**Issue by Aditya9062** [saiteja-madha/discord-js-bot#135]
**please make giveaway duration in hour , minutes , day like duration = 1hour , 1minutes , 1day**
**also in music use soundcloud or anythingelse dont use yt **
**add autorole config command in which it will show which role is for autorole .**
**add some more moderation command like rolermove , roleadd etc

**Comment by saiteja-madha** [comment]
- Human friendly duration is planned for v5
- music source is a personal choice. I can just make it configurable
- More moderation commands are planned. Not roleadd, roleremove though (since it has too much to setup and easier to be done via settings instead)

**Comment by bunnydevx** [comment]
We will look into adding that for giveaways, we will keep using YouTube, for music and in terms of more commands we are working on more!

**Comment by Adityarust** [comment]
btw v5 release when?
