### ISSUE TITLE
Music Node Error

### ISSUE THREAD

**Issue by TenTraicion** [saiteja-madha/discord-js-bot#149]
**Describe the bug**
Running `node .` or `node bot.js` the bot throws an error.

![image](https://user-images.githubusercontent.com/103281314/173618944-94b0946f-8532-4bfa-8999-fc96150972ec.png)
![image](https://user-images.githubusercontent.com/103281314/173619581-19eb8afa-5a74-4f59-8b0a-2f5635714a15.png)

and whenever running the command `/play query:..` this happens:

![image](https://user-images.githubusercontent.com/103281314/173619986-ce5beffd-e53b-400f-b997-1a28e3ee08eb.png)

**To Reproduce**
1. `node .` or `node bot.js` to run the bot and check terminal
2. `/play song_name` in discord server

**Expected behavior**
Play the mentioned music

**If possible**
 - NodeJS version: 16.15.1
 - Bot version: 4.2.3

**Comment by saiteja-madha** [comment]
The nodes are not available.
Change or add new nodes in config.js

**Comment by TenTraicion** [comment]
which nodes should i add, kindly guide me here. I am new to this. @saiteja-madha 
Thanks.

**Comment by saiteja-madha** [comment]
Look around for any free lavalink nodes.
Alternatively you can always host your own node

**Comment by TenTraicion** [comment]
Thanks a lot
