### ISSUE TITLE
Invalid OAuth2

### ISSUE THREAD

**Issue by Aflah2635** [saiteja-madha/discord-js-bot#152]
"Invalid OAuth2 redirect_uri" when i try to login to Dashboard

**Comment by Alinsert** [comment]
Do not forget to write the secret key of your bot correctly in the .env folder.
![IMG_20220630_131636](https://user-images.githubusercontent.com/69589887/176653429-6b67c773-e844-43a2-99a1-c08774a4c597.jpg)

**Comment by saiteja-madha** [comment]
Also make sure to add the dashboard url in config.js to discord developer portal
