### ISSUE TITLE
Purge Command Bug

### ISSUE THREAD

**Issue by Alinsert** [saiteja-madha/discord-js-bot#153]
**purgeuser command bug**
When using the **purgeuser** command it cannot find the messages of the user I tagged.

**Screenshots**
![purgeuser bug](https://user-images.githubusercontent.com/69589887/176673674-1322aedc-c3f1-4c7e-94d6-2c0025172fa6.png)

**If possible**
 - NodeJS version: 18.3.0
 - Bot version: 4.2.3

**Comment by saiteja-madha** [comment]
There are few limitations from discord itself. Anyways, even I noticed that purge is not consistent.
Will fix this in upcoming release
