### ISSUE TITLE
Callback Error (Ft. Add logger to find the cause)

### ISSUE THREAD

**Issue by Jonathan5508** [saiteja-madha/discord-js-bot#155]
**Describe the bug**
The callback takes you straight back to the login

**To Reproduce**
I do not know.

**Expected behavior**
Bring me the dashboard

**Screenshots**

**If possible**
 - NodeJS version: 17.9.1
 - Bot version:

**Additional context**

**Comment by TheGamer3514** [comment]
yes, i also am  having this issue!

**Comment by saiteja-madha** [comment]
Currently there isn't any logging done in dashboard for error from discord API. This will be added in v5 release.
For now just make sure that your bot secret and endpoints are correct

**Comment by saiteja-madha** [comment]
Relates to #124
