### ISSUE TITLE
07-14 06:18:39:625] [error] Search Exception : 'Unexpected token \x00 in JSON at position 0'

### ISSUE THREAD

**Issue by zairullahdev** [saiteja-madha/discord-js-bot#156]
**Describe the bug**
When searching da song

**To Reproduce**
Search song

**Expected behavior**
Searched the song

**Screenshots**

**If possible**
 - NodeJS version: 18.6.0
 - Bot version:

**Additional context**

**Comment by saiteja-madha** [comment]
I noticed few other having this issue. They fixed it by changing the node version. Anyways I am not very sure.
Feel free to join our discord and get help from others who resolved this issue

**Comment by Alinsert** [comment]
Delete package-lock.json and node-modules files. Then use node version as 16.16. It will solve your problem.
