### ISSUE TITLE
[2022-08-13 17:20:04:317] [error] Unhandled exception : 'Privileged intent provided is not enabled or whitelisted.

### ISSUE THREAD

**Issue by jaavierdz** [saiteja-madha/discord-js-bot#166]
**Describe the bug**
[2022-08-13 17:20:04:317] [error] Unhandled exception : 'Privileged intent provided is not enabled or whitelisted.

**To Reproduce**
just run it

**Expected behavior**
to run well

**Screenshots**
![imagen](https://user-images.githubusercontent.com/87701524/184504327-747f0ad4-ab90-485b-b6c9-dde828051aed.png)

**If possible**
 - NodeJS version: v16.16.0
 - Bot version: latest

**Additional context**

**Comment by jaavierdz** [comment]
OK not a bug

**Comment by saiteja-madha** [comment]
I think you got your answer! It has to do something with enabling an Intent in your discord developer portal.
Hence closing this
