### ISSUE TITLE
Client is not defined. & Json position 0 

### ISSUE THREAD

**Issue by svenbledt** [saiteja-madha/discord-js-bot#167]
**Describe the bug**
I think nothing can describe it better than the screenshot
First error was on startup
**To Reproduce**
Setup the bot with MongooseDB 6.0
use ticket setup command
**Expected behavior**
No errors?
Ticket message should be sent
**Screenshots**
![image](https://user-images.githubusercontent.com/8340034/185282667-4fdfd9c2-da84-4ae6-8772-71e02a0b81e4.png)
**If possible**
 - NodeJS version: 16.10.0
 - Bot version: 4.2.3 with some translation to my purposes

**Additional context**
[My fork](https://github.com/SoHigh495/discord-js-bot)

**Comment by svenbledt** [comment]
![image](https://user-images.githubusercontent.com/8340034/185283594-8386c40c-c145-4963-a15c-cdefd2ed7011.png)
Between this two messages i only restarted the bot. Maybe some NPM packages changed because i did no changes on the code itself. i also checked the package versions you provided and used for the project.

**Comment by svenbledt** [comment]
JSON Error occured because of VSCode backed up a package-lock.json. ----solved.

The ticket bug i still have also the /ticket limit 1 does not work.

![image](https://user-images.githubusercontent.com/8340034/185285772-7c7d4542-2f85-4544-a2db-cf7ab4ac264d.png)

**Comment by svenbledt** [comment]
i used client.user.AvatarURL() where no client was defined! Idiot incoming im sorry!

**Comment by Alinsert** [comment]
https://github.com/Uzmanist/discord-js-bot/pull/1/commits/9a9f74b3927b6a18f0927ba91d9148559f99b038
