### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by Aditya9062** [saiteja-madha/discord-js-bot#168]
after new commit in help cmd not working its showing error while using dropdown menu

![image](https://user-images.githubusercontent.com/95363688/187239543-810aff14-ada9-458e-8c0c-6cca58727e88.png)

**If possible**
 - 17.8.0
 - v5

**Comment by saiteja-madha** [comment]
I would have to see the complete error details from logs/ directory

**Comment by Adityarust** [comment]
> I would have to see the complete error details from logs/ directory

{"type":"CombinedError","message":"Received one or more errors","stack":"Error: Received one or more errors\n    at UnionValidator.handle (C:\Users\\node_modules\@sapphire\shapeshift\dist\index.js:1085:23)\n    at UnionValidator.parse (C:\User\node_modules\@sapphire\shapeshift\dist\index.js:142:88)\n    at EmbedBuilder.setThumbnail (C:\Users\node_modules\@discordjs\builders\dist\messages\embed\Embed.cjs:76:34)\n    at getMsgCategoryEmbeds (C:\Usersv\src\commands\utility\help.js:313:8)\n    at InteractionCollector.<anonymous> (C:\Users\src\commands\utility\help.js:156:30)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","errors":[{"name":"Error","validator":"s.nullish","given":""},{"name":"Error","constraint":"s.string.url","given":"","expected":"expected to match an URL"}]},"msg":"Unhandled exception: Received one or more errors"} whole erroe

**Comment by Adityarust** [comment]
> I would have to see the complete error details from logs/ directory

Bug fixed for not??

**Comment by saiteja-madha** [comment]
I wasn't able to replicate this bug. Did you try with a fresh copy of version 5?

**Comment by erutluZ** [comment]
try copy v5 clean and change node version to 16.*.*

**Comment by saiteja-madha** [comment]
Closing this. Could not be replicated
