### ISSUE TITLE
Error on command "play"

### ISSUE THREAD

**Issue by rozeen-shrestha** [saiteja-madha/discord-js-bot#171]
**Describe the bug**
Whenever i use play command the song is added to the queue but doesnot play it just ends.

**Expected behavior**
I want it to actually play the song.

**Screenshots**
https://media.discordapp.net/attachments/1010119951006318673/1014522266899468378/unknown.png?width=500&height=238

**If possible**
 - NodeJS version:16
 - Bot version:latest
\

**Comment by erutluZ** [comment]
check log and recheck node

**Comment by Alinsert** [comment]
Changing the Lavalink server may solve your problem.
