### ISSUE TITLE
Failed to login to dashboard 

### ISSUE THREAD

**Issue by TheGamer3514** [saiteja-madha/discord-js-bot#173]
**Describe the bug**
Whenever i try login to dashboard it gives error "Failed to login to dashboard " to console
![image](https://user-images.githubusercontent.com/79448904/187899702-e095f286-18e8-4345-b093-f6da581d6358.png)

**To Reproduce**
Login to the dashboard

**Expected behavior**
For it to log me in to the dashboard

**If possible**
 - NodeJS version: 17.9.1
 - Bot version: Latest

**Additional context**

**Comment by saiteja-madha** [comment]
Check the logs folder for more details

**Comment by TheGamer3514** [comment]
Fixed
