### ISSUE TITLE
Ticket Setup doesnt work

### ISSUE THREAD

**Issue by svenbledt** [saiteja-madha/discord-js-bot#177]
**Describe the bug**
When i try to use /ticket setup it tells me an error occured
**To Reproduce**
use /ticket setup with v5
**Expected behavior**
Should create a ticket setup message but doesnt
**Screenshots**
not needed i think no debug output in console

**If possible**
 - NodeJS version: 16.10.0
 - Bot version: 5.0.0

**Additional context**
I merged with some language changes but double checked everything.

Atm i reverted my changes to get it work again

**Comment by saiteja-madha** [comment]
It works for me. You can join our discord to discuss further

**Comment by Kimzzxf** [comment]
> It works for me. You can join our discord to discuss further

The link has expired, can you renew?

**Comment by saiteja-madha** [comment]
> > It works for me. You can join our discord to discuss further
> 
> The link has expired, can you renew?

Please use this https://discord.gg/2gPy75zgbW
