### ISSUE TITLE
client error

### ISSUE THREAD

**Issue by TheNotoriousChicken** [saiteja-madha/discord-js-bot#179]
i dont know how this error was caused even tho i filled everything properly
![Screenshot (393)](https://user-images.githubusercontent.com/98900607/191274542-c7ea1ced-b8fe-44a4-9346-5bd6e23641e4.png)

**Comment by xitrumcute** [comment]
i am also getting this error

**Comment by saiteja-madha** [comment]
> i dont know how this error was caused even tho i filled everything properly ![Screenshot (393)](https://user-images.githubusercontent.com/98900607/191274542-c7ea1ced-b8fe-44a4-9346-5bd6e23641e4.png)

You have duplicates in your guilds collection. If you are using any old collection, switch to a new database
