### ISSUE TITLE
Client Error

### ISSUE THREAD

**Issue by xitrumcute** [saiteja-madha/discord-js-bot#180]
![error](https://user-images.githubusercontent.com/106767375/191296219-caf981fa-ab3f-4ef5-83b1-501309ad7711.png)
how to fix Client Error?

**Comment by saiteja-madha** [comment]
Can you check the logs/ folder for further details?
Also when did you get this error? (On startup or migration?)

**Comment by xitrumcute** [comment]
On startup

**Comment by saiteja-madha** [comment]
I cannot replicate this.
You may join our discord to discuss further
