### ISSUE TITLE
Suggestion not working

### ISSUE THREAD

**Issue by magoxado** [saiteja-madha/discord-js-bot#181]
In the config file i set it to true but the bot say Suggestion system is disabled. idk what is the problem. can you help?

**Comment by saiteja-madha** [comment]
> In the config file i set it to true but the bot say Suggestion system is disabled. idk what is the problem. can you help?

Setting it to true will enable the suggestions category. You still need to enable/disable that system in your server 
`!suggestion status on>

**Comment by magoxado** [comment]
thanks
