### ISSUE TITLE
Disable / Enable Commands

### ISSUE THREAD

**Issue by erwinowak** [saiteja-madha/discord-js-bot#182]
**Disable / Enable Commands**
I thought about a command that will enable and disable selected commands.

**Comment by saiteja-madha** [comment]
> **Disable / Enable Commands** I thought about a command that will enable and disable selected commands.

Yes that would be cool. As of now only owners can enable or disable commands
You mean a command that let's guild owner disable commands?

**Comment by erwinowak** [comment]
> Yes that would be cool. As of now only owners can enable or disable commands
> You mean a command that let's guild owner disable commands?

How can the owner turn commands off and on?

It would be nice if the server owner could turn off commands on his server

**Comment by erwinowak** [comment]
> Yes that would be cool. As of now only owners can enable or disable commands
> You mean a command that let's guild owner disable commands?

How can the owner turn commands off and on?
