### ISSUE TITLE
Anti Invite not work.

### ISSUE THREAD

**Issue by C0SMOS-X** [saiteja-madha/discord-js-bot#184]
Hello,
The anti prompt is not working.
We can still put discord.gg/invite that is not deleted.

**Comment by jordan-adelle** [comment]
Anti invite*

**Comment by saiteja-madha** [comment]
I have just tested it and it works.
By default the bot doesn't moderate messages sent by moderators (i.e. those who have Manage Server, Kick, Ban permissions)

You can change this by setting `!automod debug on`

**Comment by jordan-adelle** [comment]
Weird, because I tried with an account that was not moderating.

**Comment by saiteja-madha** [comment]
> Weird, because I tried with an account that was not moderating.

If it still doesn't work, join our discord and we can talk over
