### ISSUE TITLE
Bigemoji.js

### ISSUE THREAD

**Issue by C0SMOS-X** [saiteja-madha/discord-js-bot#190]
Problem with bigemoji

![image](https://user-images.githubusercontent.com/52496524/192508482-66b90d6a-5310-458f-a206-4ea1c899df3f.png)

**Comment by saiteja-madha** [comment]
Please provide complete error log related to this error from /logs folder

**Comment by saiteja-madha** [comment]
Cannot replicate this issue. Hence closing this
