### ISSUE TITLE
Problem on giveaway setup

### ISSUE THREAD

**Issue by C0SMOS-X** [saiteja-madha/discord-js-bot#191]
![image](https://user-images.githubusercontent.com/52496524/192523129-016b0f4b-68ad-4dd5-a2d1-b25ce265a8c0.png)

**Comment by saiteja-madha** [comment]
This is something I'll have to check. Thanks for reporting
If you manage to find a fix, you may raise a PR

**Comment by saiteja-madha** [comment]
@KINGK0NG-V1 Could you add the steps to replicate this error?
