### ISSUE TITLE
List Servers Command

### ISSUE THREAD

**Issue by TheGamer3514** [saiteja-madha/discord-js-bot#195]
**Describe the bug**
List Servers Command Says: This command is only accessible to bot owners

**To Reproduce**
Do List Servers Command

**Expected behaviour**
I Expect It To List Servers

**If possible**
 - NodeJS version: 18.9.0
 - Bot version: Latest

**Additional context**
Config.js Properly Setup

**Comment by saiteja-madha** [comment]
You need to add your ID in ownerID's section of config.js

**Comment by TheGamer3514** [comment]
I have

**Comment by saiteja-madha** [comment]
> I have

Did you add it as an array of values?

**Comment by TheGamer3514** [comment]
``  OWNER_IDS: [763471049894527006], // Bot owner ID's``
that is config for owner id

**Comment by saiteja-madha** [comment]
If the ID is correct, then it should work
