### ISSUE TITLE
Timeout command

### ISSUE THREAD

**Issue by airwavdev** [saiteja-madha/discord-js-bot#196]
**Describe the bug**
When trying to timeout a USER it returns `NaN is not a function` error

**Screenshots**
![image](https://user-images.githubusercontent.com/80008084/193428856-25fedd7a-cf83-4213-afc1-767c6baf96fa.png)

**If possible**
 - NodeJS version: v16.17.0
 - Bot version: v5.0.1

**Comment by saiteja-madha** [comment]
This will be fixed in upcoming release
