### ISSUE TITLE
Related to something new CFX

### ISSUE THREAD

**Issue by swastik-mohanty** [saiteja-madha/discord-js-bot#201]
**Is your command request related to a problem? Please describe.**

**Describe what command you'd like**

**Additional context**

**Comment by saiteja-madha** [comment]
What do you mean? 
I did not quite understand

**Comment by saiteja-madha** [comment]
Seems like you opened another issue. Hence closing this

**Comment by swastik-mohanty** [comment]
yeah close this one check the latest one
