### ISSUE TITLE
Related to CFX Stats

### ISSUE THREAD

**Issue by swastik-mohanty** [saiteja-madha/discord-js-bot#203]
Please Add CFX stats in presence.js using cfx-api like 

```var liveServer = await cfx.fetchServer(FiveMServerID)
 client.user.setActivity({

                            name:`Players: ${liveServer.playersCount}/${liveServer.maxPlayers}`, type: 'WATCHING'
                });```

**Comment by kanetjuh** [comment]
Make a request where you get the json info from `<fivem-server-ip>:30120/info.json` and then get the max and player count from their.

**Comment by Anonghost720** [comment]
Maybe i share my cfx command code

**Comment by swastik-mohanty** [comment]
@Anonghost720 sure thanks

**Comment by Anonghost720** [comment]
so far is looking like this https://i.imgur.com/jkTmosU.png

**Comment by swastik-mohanty** [comment]
@Anonghost720 can you send me the code or Api

**Comment by Anonghost720** [comment]
Is not an api i just coded it using parsing whatever server json files

**Comment by Anonghost720** [comment]
I can show u what i did if need it

**Comment by swastik-mohanty** [comment]
@Anonghost720 yes plz send it to me

**Comment by swastik-mohanty** [comment]
> I can show u what i did if need it

yes please

**Comment by Anonghost720** [comment]
I will, sorry i been busy, i also need your help with something, what's your discord?

**Comment by kanetjuh** [comment]
> I will, sorry i been busy, i also need your help with something, what's your discord?

What's up?

**Comment by saiteja-madha** [comment]
@swastik-mohanty Feel free to join support discord for getting custom help
https://discord.com/invite/2gPy75zgbW
