### ISSUE TITLE
Cant run npm i

### ISSUE THREAD

**Issue by ArashSeyfi** [saiteja-madha/discord-js-bot#209]
npm notice 
npm notice New minor version of npm available! 8.11.0 -> 8.19.2
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.19.2>
npm notice Run `npm install -g npm@8.19.2` to update!
npm notice 
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/menudocs/erela.js.git
npm ERR! ssh -oStrictHostKeyChecking=accept-new: 1: ssh -oStrictHostKeyChecking=accept-new: ssh: not found
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

**Comment by saiteja-madha** [comment]
This has been fixed
