### ISSUE TITLE
Owner id

### ISSUE THREAD

**Issue by magoxado** [saiteja-madha/discord-js-bot#214]
its not that complicated, um i put my id to the config, but it says: 
This command is only accessible to bot owners

**Comment by magoxado** [comment]
![image](https://user-images.githubusercontent.com/99046257/197397210-264690a9-1e93-4511-85d4-b8d1c3b0f8a5.png)

**Comment by saiteja-madha** [comment]
This should work. Can you check if owner ID is correct

**Comment by 7331vrk** [comment]
remove the [ ] and it should work, i had the same problem

**Comment by saiteja-madha** [comment]
It should be of type string
