### ISSUE TITLE
New Image API

### ISSUE THREAD

**Issue by saiteja-madha** [saiteja-madha/discord-js-bot#227]
Migrate to new API https://strangeapi.fun
New Endpoint: `/overlay`

**Comment by Anonghost720** [comment]
Hey can you update the dashboard to some like mee6 or some?

**Comment by Jonathan5508** [comment]
How to make the authorization work to this so the image manipulation will work

**Comment by saiteja-madha** [comment]
> How to make the authorization work to this so the image manipulation will work

It goes in the header as `Authorization: Bearer {TOKEN}`
I will be raising a PR for this feature shortly

**Comment by saiteja-madha** [comment]
You can check this PR for changes #229 
It will be released in v5.1.0

**Comment by mrkingtj** [comment]
This new API doesn't work as the site is constantly down

**Comment by nooksmr** [comment]
Still down as of 2025 apparently.
