### ISSUE TITLE
Counter Status Error

### ISSUE THREAD

**Issue by guiltysyndicate** [saiteja-madha/discord-js-bot#24]
File: counter-setup.js
Error: TypeError: db.getSettings is not a function
Fix: Change line 74 from 'const config = await db.getSettings(guild.id);' to 'const config = await db.getConfig(guild.id);'
    const config = await db.getConfig(guild.id);

**Comment by saiteja-madha** [comment]
Thanks @guiltysyndicate
Fixed this
