### ISSUE TITLE
ERROR: messageRun: Cannot read properties of undefined (reading 'track')

### ISSUE THREAD

**Issue by NoBody-IDK** [saiteja-madha/discord-js-bot#243]
**Describe the bug**
When in config.js =  `DEFAULT_SOURCE: "SC"` music not working i get multiple errors. but the main one is this:
![image](https://user-images.githubusercontent.com/58013305/201845867-11169312-4c85-4098-b434-4f08ae6ef7ec.png)

Other Errores:
![image](https://user-images.githubusercontent.com/58013305/201846050-2f8de9a5-2582-4a2a-92a0-a12d23cd1960.png)

**To Reproduce**
Using the command `/play`

**If possible**
 - NodeJS version: v17.1.0
 - Bot version: 5.1.0

**Additional context**
To add when `DEFAULT_SOURCE: "YT"`, the command worked correctly.
I hope a solution for the search with SC, TY.

**Comment by Jonathan5508** [comment]
Hello! I cannot seem to produce this error, can you tell me exactly what you did to get these errors?

**Comment by NoBody-IDK** [comment]
only when using `/play`

**Comment by saiteja-madha** [comment]
Unable to replicate this! Anyways added more debug loggers to investigate
