### ISSUE TITLE
/Bassboost not working

### ISSUE THREAD

**Issue by patrekurlol** [saiteja-madha/discord-js-bot#250]
**Describe the bug**
Everytime I do /bassboost any level it doesnt work i keep getting ERROR: safeReply: Invalid Form Body
message_reference[REPLIES_UNKNOWN_MESSAGE]: Unknown message

**To Reproduce**
Steps to reproduce the behavior:/Bassboost

**Expected behavior**
Bassboost the music

**Screenshots**

**If possible**
 - NodeJS version:16.11.0
 - Bot version: 5.1.0

**Additional context**

**Comment by saiteja-madha** [comment]
Cannot replicate this
