### ISSUE TITLE
Rank channel not work

### ISSUE THREAD

**Issue by C0SMOS-X** [saiteja-madha/discord-js-bot#258]
Good evening,
When you choose a channel, it does not go to the channel in question, but to the channel where the message was sent.

**Comment by ghost** [comment]
Still not sending messages

**Comment by Anonghost720** [comment]
Did you setup your database correctly?

**Comment by ghost** [comment]
yes, I installed it correctly the information is uploaded to the db but the bot does not send now I remember it doesn't send logs either

**Comment by Anonghost720** [comment]
Does the bot has correct perms

**Comment by ghost** [comment]
![db_ss](https://user-images.githubusercontent.com/104034860/204399556-177110e7-5e21-47f6-9f59-4106ee4348e3.png)
have admin perms and there is no error in my console

**Comment by Anonghost720** [comment]
Ok when i get home ill help you

**Comment by Jonathan5508** [comment]
When I approved this, it worked great

**Comment by ghost** [comment]
idk why it's not working for me

**Comment by Jonathan5508** [comment]
Can you send your code of that file in a https://sourceb.in

**Comment by ghost** [comment]
https://sourceb.in/KRk9KC4T8D here

**Comment by Jonathan5508** [comment]
Why is there this massive and statement
![AD616128-04DC-499B-9768-084F2B51B844](https://user-images.githubusercontent.com/102492309/205062252-b0ef06c8-56cc-4787-ba73-fb550bbde342.png)

**Comment by Jonathan5508** [comment]
relooking at it, it's correct, it works for me on multiple bots
