### ISSUE TITLE
Warn Command Not Working

### ISSUE THREAD

**Issue by editlt** [saiteja-madha/discord-js-bot#264]
**Describe the bug**
In the source code of the bot, the warn command for me didn't work, I copied it word for word to even test it, and it didn't show up in  the slash command menu and the ! prefix for warnings and warn didn't work. Those are the only commands in the moderation folder, so unless I need to call on it for it to work, it doesnt.

**To Reproduce**
Fix?

**Expected behavior**
The command to show up in the slash command menu and warn the user. For warnings: to show the warning.

**Screenshots**

**If possible**
 - NodeJS version:
 - Bot version: 14.6.0

**Additional context**
N/A

**Comment by Jonathan5508** [comment]
@EditlT show me config.js file

**Comment by Jonathan5508** [comment]
And 14.6.0 is not a valid version, I assume that's a discord.js version.

**Comment by editlt** [comment]
Yes 14.6.0 is my DJS version, and I found the error within the code, but it doesn't make sense as I 100% copied it within the code in warn.js, nevermind then. 

Thanks for helping anyway 😅

**Comment by Jonathan5508** [comment]
@EditlT what is the issue
