### ISSUE TITLE
invalid Oauth2 redirect_uri

### ISSUE THREAD

**Issue by vexato** [saiteja-madha/discord-js-bot#269]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![Capture](https://user-images.githubusercontent.com/111609508/206177459-1733c8af-0331-48b4-a2a3-a83649343922.PNG)

**If possible**
 - NodeJS version: lastest
 - Bot version: latest

**Additional context**
to connect dasboard

sorry i am french men

**Comment by NoBody-IDK** [comment]
https://docs.strangebot.fun/additional/installation#setting-up-dashboard

**Comment by vexato** [comment]
thank you
