### ISSUE TITLE
Include MongoDB configuration in the Dockerfile

### ISSUE THREAD

**Issue by tjr5269** [saiteja-madha/discord-js-bot#270]
**Is your feature request related to a problem? Please describe.**
Include MongoDB configuration in the Dockerfile

**Describe the solution you'd like**
Include MongoDB configuration in the Dockerfile

**Describe alternatives you've considered**

**Additional context**

**Comment by saiteja-madha** [comment]
> **Is your feature request related to a problem? Please describe.** Include MongoDB configuration in the Dockerfile
> 
> **Describe the solution you'd like** Include MongoDB configuration in the Dockerfile
> 
> **Describe alternatives you've considered**
> 
> **Additional context** Add any other context or screenshots about the feature request here.

I completed forgot about this. Thanks
This will be done as part of next release

**Comment by Anonghost720** [comment]
Why some events dont work like memberban, streaming start and more?

**Comment by saiteja-madha** [comment]
This is now part of the docker-compose file
