### ISSUE TITLE
Discord Bot Dashboard

### ISSUE THREAD

**Issue by shadowgamer1337ttv** [saiteja-madha/discord-js-bot#281]
i dont know if this is a bug, but if i go to the dashboard in the about embed it says: "invalid OAuth2 redirect_uri" 
![Screenshot 2022-12-13 13:52:19](https://user-images.githubusercontent.com/105737896/207349082-3b10e3ca-d31a-4a12-9346-edc9779b784a.png)

**Comment by Dark25** [comment]
It is not a code error, you must add your url
