### ISSUE TITLE
Problem with the new update 5.2.0 (dashboard)

### ISSUE THREAD

**Issue by C0SMOS-X** [saiteja-madha/discord-js-bot#284]
**Describe the bug**
Unable to access the bot dashboard since the new update

**Screenshots**
![image](https://user-images.githubusercontent.com/52496524/208246687-a83ae49e-5675-4fe3-b531-2cd93dd8cff4.png)
![image](https://user-images.githubusercontent.com/52496524/208246696-e4561f02-b6cd-484d-a43b-3d0df625dbf8.png)

**If possible**
 - NodeJS version:
 - Bot version: 5.2.0

**Comment by Anonghost720** [comment]
Same issue

**Comment by Dark25** [comment]
how did you get this error?

**Comment by jordan-adelle** [comment]
> how did you get this error?

As said before this happens with update 5.2.0

**Comment by Dark25** [comment]
I understand, but since you cause the error, so you can repair it

**Comment by saiteja-madha** [comment]
Try using the latest version of the bot. If the issue still persists, feel free to re-open this PR
