### ISSUE TITLE
/play not working 

### ISSUE THREAD

**Issue by Aendirr** [saiteja-madha/discord-js-bot#293]
I do "/play", but the slash command does not appear and I cannot search. And it doesn't work on some commands. I may have done the installation wrong. Can you reach me on discord? For installation

**Comment by editlt** [comment]
In your config.js file, make sure you have the MUSIC {} category enabled otherwise nothing will show up. Also, what is your discord?

**Comment by saiteja-madha** [comment]
Try using the latest version and check if the issue persists
