### ISSUE TITLE
Bot doesn't detect owner ids

### ISSUE THREAD

**Issue by ghost** [saiteja-madha/discord-js-bot#294]
![image](https://i.imgur.com/NWrwWO3.png)
Already added my id on the bot but...
![image2](https://i.imgur.com/iSy72vb.png)

Please fix this error 👍

**Comment by editlt** [comment]
You need to add " " for your owner id. e.g. 

`OWNER_IDS: ["1013236808353599488"],`

**Comment by ghost** [comment]
Thank you it worked 👍
