### ISSUE TITLE
Events file for ready.js

### ISSUE THREAD

**Issue by LoopyChimp** [saiteja-madha/discord-js-bot#3]
Hello! i was just wondering how i could go about adding an events file for ready.js aand other files

**Comment by saiteja-madha** [comment]
You just need to create a **YOUR_FEATURE**.js file in `src/features` folder and export a `run(client)` function
```
module.exports.run = (client) => {
// Do your startup stuff here

    // listen for your own client events here
    client.on('', (args) => {

    });
}
```
This function is automatically invoked when the ready event is fired 🔥

**Comment by LoopyChimp** [comment]
> You just need to create a **YOUR_FEATURE**.js file in `src/features` folder and export a `run(client)` function
> 
> ```
> module.exports.run = (client) => {
> // Do your startup stuff here
> 
>     // listen for your own client events here
>     client.on('', (args) => {
> 
>     });
> }
> ```
> 
> This function is automatically invoked when the ready event is fired 🔥

thanks so much ill add this now!
