### ISSUE TITLE
ERROR: Client Error: guild validation failed: undefined: Cannot read properties of undefined (reading 'options')

### ISSUE THREAD

**Issue by DEKKEXSA** [saiteja-madha/discord-js-bot#300]
**Describe the bug**
Guys I have Client Error
Cannot read properties of undefined (reading 'options')

**To Reproduce**

**Expected behavior**

**Screenshots**

**If possible**
 - NodeJS version:
 - Bot version:

**Additional context**

**Comment by saiteja-madha** [comment]
Need more info to replicate this. Try using the latest version to see if the issue is resolved
