### ISSUE TITLE
Mongo database

### ISSUE THREAD

**Issue by brioch77** [saiteja-madha/discord-js-bot#302]
hey hello,im new in coding, what's "`# Mongo Database Connection String` "?
is it mongodb?
and where can i found the `mongo_connection`?

also where can i find in discord developer portal the

```
BOT_SECRET=
SESSION_PASSWORD=
```

thank you

**Comment by cfmaniac** [comment]
@brioch77 :
The MongoDB Connection String is Given to you when you've either installed Mongo Atlas or using the mongodb Cloud.
The Connection String Looks like: 
mongodb://[username:password@]host1[:port1][,...hostN[:portN]][/[defaultauthdb][?options]]
