### ISSUE TITLE
Dashboard URL redirecting to 0auth2 page

### ISSUE THREAD

**Issue by luckyoi** [saiteja-madha/discord-js-bot#318]
When I try opening up https://myvpsip:8080 as set in `config.js`
```
  DASHBOARD: {
    enabled: false, // enable or disable dashboard
    baseURL: "http://myvpsip:8080", // base url
    failureURL: "http://myvpsip:8080", // failure redirect url
    port: "8080", // port to run the bot on
  },

```
I go to authorisation page on 0auth2 and I added my bot to the server I wanted.
This is my redirection url: https://prnt.sc/RbcwUO7ci9jF
After that, I head over to https://myvpsip:8080 to login to dashboard but instead it keeps redirecting me to the 0auth2 page.

 - NodeJS version: 14x latest
 - Bot version: latest

I found someone had same problem but no solution for that issue.
https://github.com/saiteja-madha/discord-js-bot/issues/43

**Comment by saiteja-madha** [comment]
Seems like there was an error which is causing you to redirect back to login page since `failureURL` in config.js is same as `baseURL`. I have added loggers which can help find the exact cause 
Check commit: 9b213a68c80a7b568e3425db325f1e23dfdb3473

**Comment by cfmaniac** [comment]
@saiteja-madha :
One of the Errors, I've recieved from this the updated discord.js file is:

user_id[NUMBER_TYPE_COERCE]: Value "null" is not snowflake.

So It Looks like the the userID is returning null on the Authorization Process

**Comment by saiteja-madha** [comment]
Follow the steps in the docs and it should work. Alternatively, feel free to join our Discord server.
