### ISSUE TITLE
When update stuff in the dashboard get error

### ISSUE THREAD

**Issue by BigglesDevs** [saiteja-madha/discord-js-bot#325]
**Describe the bug**
When making changes in the dashboard it not working

**To Reproduce**
When i select the the update button it dose not update the bot behaviour a error will pop up saying

       ERROR: Client Error: The reply to this interaction has not been sent or deferred.

**Expected behavior**
Its suppose to update the bot when i click update, this does not happen and is suppose to make it easy

**Screenshots**
![image](https://user-images.githubusercontent.com/103225055/227835416-ba1a753e-1091-4aea-aac0-9078f18e4c74.png)

**If possible**
 - NodeJS version:
 - Bot version: latesst 

**Additional context**

**Comment by saiteja-madha** [comment]
Can you share the error logs from "/logs" folder

**Comment by saiteja-madha** [comment]
Try using the latest version
