### ISSUE TITLE
Dashboard error user_id

### ISSUE THREAD

**Issue by AC1Studios** [saiteja-madha/discord-js-bot#326]
Unhandled exception: Invalid Form Body
user_id[NUMBER_TYPE_COERCE]: Value "null" is not snowflake.

this is the error I'm getting
![image](https://user-images.githubusercontent.com/71151528/228722028-4135531b-6ffc-4080-8b9b-30ecb27f569b.png)

**Comment by AC1Studios** [comment]
any help on fixing this?

**Comment by AC1Studios** [comment]
I added this code and definitely has an issue trying to retrieve the user.id
 if (!userData || !userData.id) {
    throw new Error("Invalid user data: missing user ID");
  }

**Comment by saiteja-madha** [comment]
> Unhandled exception: Invalid Form Body user_id[NUMBER_TYPE_COERCE]: Value "null" is not snowflake.
> 
> this is the error I'm getting ![image](https://user-images.githubusercontent.com/71151528/228722028-4135531b-6ffc-4080-8b9b-30ecb27f569b.png)

Could you share the error logs from "/logs" folder

**Comment by AC1Studios** [comment]
It doesn't even log the errors except for the console. I can be more specific about what's going on. After authorizing the discord bot to log in to the dashboard, my user or anyone it throws this error `ERROR: Unhandled exception: Invalid Form Body
user_id[NUMBER_TYPE_COERCE]: Value "null" is not snowflake.` It looks like the userData.id is null, causing this error. I need help figuring out how to fix this. Cause with this error it doesn't redirect the web to the /selector

**Comment by saiteja-madha** [comment]
Follow the steps in the docs and it should work. Alternatively, feel free to join our Discord server.
