### ISSUE TITLE
/info guild error

### ISSUE THREAD

**Issue by N0rule** [saiteja-madha/discord-js-bot#334]
**Describe the bug**
when i try to use /info guild it gives error, for some reason on my test server, it works fine.

**To Reproduce**
1. start bot using npm run start
2. use /info guild
3. got error (see screenshot below)

**Expected behavior**
1. start bot using npm run start
2. use /info guild
3. get information
![image](https://user-images.githubusercontent.com/30196774/230902615-01762505-0e9d-4dfb-b6ee-1bfcd9242086.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/30196774/230902350-c444e3ce-bc32-44f8-bc0b-52c8830fee70.png)

**If possible**
 - NodeJS version: v18.14.2  
 - Bot version:  v5.2.0

**Comment by saiteja-madha** [comment]
This should be fixed in the latest version. Alternatively, feel free to reopen this PR.
