### ISSUE TITLE
Error: Cannot find module '/home/runner/discord-js-bot-1/index.js'

### ISSUE THREAD

**Issue by AhmedElguker** [saiteja-madha/discord-js-bot#336]
Error: Cannot find module '/home/runner/discord-js-bot-1/index.js'
Require stack:
- /nix/store/qpnf0dafrfsbcwb4z7cphjm0dff0vl7l-prybar-nodejs-0.0.0-e0d9a52/prybar_assets/nodejs/module-context-hook.js
- /tmp/prybar-nodejs-440005136.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)

**Comment by Korawith** [comment]
just rename the bot.js file to index,js

**Comment by saiteja-madha** [comment]
Yes the entry point is bot.js and not index.js
