### ISSUE TITLE
Dashboard do not work

### ISSUE THREAD

**Issue by AhmedElguker** [saiteja-madha/discord-js-bot#337]
The dashboard do not work

**Comment by AC1Studios** [comment]
you have to elaborate? what are your error logs?

**Comment by ductridev** [comment]
@AhmedElguker Can you please share your `config.js`?

**Comment by LeGi0N09** [comment]
you have to enable it in config.js and add your webview link instead of localhost links

**Comment by saiteja-madha** [comment]
Follow the steps in the docs and it should work. Alternatively, feel free to join our Discord server.
