### ISSUE TITLE
Not sure what to name this

### ISSUE THREAD

**Issue by dropalways** [saiteja-madha/discord-js-bot#338]
**Describe the bug**
Crashes the program

**To Reproduce**
.help then click a category

**Expected behavior**
show what the help does

**Screenshots**
https://r2.e-z.host/20aca75f-b614-4a0a-af4a-a562b0905973/bfjqdwac.png

**If possible**
 - NodeJS version:18.12.1
 - Bot version: i have no idea

**Additional context**

**Comment by tro1fake** [comment]
I have the same problem

**Comment by saiteja-madha** [comment]
Fixed as part of 5.3.0 release
