### ISSUE TITLE
Music Commands

### ISSUE THREAD

**Issue by AgentDeath253** [saiteja-madha/discord-js-bot#344]
**Describe the bug**
When trying to search a song or play the song it gives and error

**To Reproduce**
Do all the config to start the bot, do the search or play command (prefix or slash) and then see the error

**Expected behavior**
Bot Successfully Plays the Song/Searches the Song

**Screenshots**
![image](https://user-images.githubusercontent.com/82530339/233518771-e993bc23-7d7d-4bce-af31-27a4d85f668b.png)

**If possible**
 - NodeJS version: 16.11.0
 - Bot version: Latest Release

**Additional context**
N/A

**Comment by ductridev** [comment]
@AgentDeath253 Can you please share your `config.js`?

**Comment by LeGi0N09** [comment]
its because Lavalink server not working you need to change Lavalink

**Comment by LeGi0N09** [comment]
{
        host: "lava1.horizxon.studio",
        port: 80,
        password: "horizxon.studio",
        id: "Music Client",
        retryDelay: 5000,
        secure: false,
      },

**Comment by LeGi0N09** [comment]
like and coment
