### ISSUE TITLE
Strange API is not working

### ISSUE THREAD

**Issue by VedicXcel-Innovations** [saiteja-madha/discord-js-bot#355]
**Describe the bug**
Strange API is not working, showing API error when using image command.

**Screenshots**
![IMG_20230510_095429](https://github.com/saiteja-madha/discord-js-bot/assets/74998268/d347e838-a94a-4c41-bfb1-5836132f3499)

**If possible**
 - NodeJS version: Latest
 - Bot version: Latest

**Additional context**
Generated Strange API key by login into their Dashboard using same Discord ID which is the BOT owner ID.

**Comment by EdVoids** [comment]
Animal Command is not come from Strange API. 
Check look at this Pull Request to help you out

https://github.com/saiteja-madha/discord-js-bot/pull/353#issue-1699793579

**Comment by VedicXcel-Innovations** [comment]
Thanks to @EdVoids for the fixes. Everything is working fine now. Please merge with the rectifications.

**Comment by mrkingtj** [comment]
Its impossible to generate an API key nowdays
