### ISSUE TITLE
Dashboard not working

### ISSUE THREAD

**Issue by UnknownvLeaf** [saiteja-madha/discord-js-bot#356]
**Describe the bug**
I used replit to use the bot. In my config file its https://replname.username.repl.co and in the OAuth page its https://replname.username.repl.co/callback

**Expected behavior**
The website should load up but when I actually run it, it says invalid oauth redirect uri

**If possible**
 - NodeJS version:16.20.0
 - Bot version:5.2.0

**Comment by LeGi0N09** [comment]
Try it some time letter and Open Web page in different  tab of window

**Comment by jindalpriyanshu101** [comment]
i think it should be `https://replname.username.repl.co/api/callback` instead of `https://replname.username.repl.co/callback`

and also add another URI, `https://replname.username.repl.co/selector` it'll work if you have made correct configs

**Comment by rhaym-tech** [comment]
replit users being replit users

**Comment by ANIKETEDITZ** [comment]
> i think it should be `https://replname.username.repl.co/api/callback` instead of `https://replname.username.repl.co/callback`
> 
> and also add another URI, `https://replname.username.repl.co/selector` it'll work if you have made correct configs

Didn't work for me

**Comment by saiteja-madha** [comment]
Follow the steps in the docs and it should work. Alternatively, feel free to join our Discord server.
