### ISSUE TITLE
Where can i find "SESSION_PASSWORD=" from the .env file?

### ISSUE THREAD

**Issue by korauo** [saiteja-madha/discord-js-bot#364]
Where can i find "SESSION_PASSWORD=" from the .env file?

**Comment by barrierunlocked** [comment]
Nowhere. It's the password you set first time there, put anything you want. With that password you'll login to the panel.

**Comment by MSaeed-14** [comment]
> Nowhere. It's the password you set first time there, put anything you want. With that password you'll login to the panel.

But does the dashboard work?
