### ISSUE TITLE
Slash command not working 

### ISSUE THREAD

**Issue by Sandy00702** [saiteja-madha/discord-js-bot#368]
Can someone help me with this ?

![02](https://github.com/saiteja-madha/discord-js-bot/assets/97554183/ce41579f-162c-4f1a-a73b-38aa8f50f7e7)
![01](https://github.com/saiteja-madha/discord-js-bot/assets/97554183/2388e374-121b-4c8d-9817-b421ce2a4c6a)

**Comment by Discobotdevlolhehe** [comment]
npm i discord.js@latest

**Comment by iamvikshan** [comment]
Update your bot to [V5.4.0](https://github.com/saiteja-madha/discord-js-bot/releases/tag/5.4.0) and update your dependencies with
```bash
npm i
```
