### ISSUE TITLE
ERROR: .env bot token cannot be empty

### ISSUE THREAD

**Issue by kitkatgucci** [saiteja-madha/discord-js-bot#369]
So basically when I try to run the bot after filling out the info it keeps saying that the bot token in .env is empty, yet it isn't empty at all and I filled it in already. I am new to this so that's why I need a bit of help.

**Comment by isaewwxx** [comment]
If you are using replit or glitch when you are in your repl, navigate to the secrets tab and add the token value. If you are using a program like Visual Studio, dont use quotes and spaces when you are in the .env file. I hope that helps!
