### ISSUE TITLE
Lvlup bug

### ISSUE THREAD

**Issue by Bleee411** [saiteja-madha/discord-js-bot#384]
**Describe the bug**
A lvlup messages didnt show member who get new lvl 

**Screenshots**

![Screenshot_2023-07-09-20-21-32-82_572064f74bd5f9fa804b05334aa4f912.png](https://github.com/saiteja-madha/discord-js-bot/assets/134770202/655b1232-fa2b-4f45-ae5d-b4c81aa55fa2)

**Comment by saiteja-madha** [comment]
These are the available message replacements.
```
\n - new line
{server} - server name
{count} - server member count
{member:id} - member id
{member:name} - member name
{member:mention} - member mention
{member:tag} - member tag
{level} - level
```
