### ISSUE TITLE
Invalid redirect uri

### ISSUE THREAD

**Issue by knifeworm** [saiteja-madha/discord-js-bot#39]
**Describe the bug**
Invalid Redirect uri
**To Reproduce**
go to the dashboard and try and login

**Expected behavior**
login me in
**Screenshots**
![image](https://user-images.githubusercontent.com/77696553/136688276-d3524cb6-6eed-4299-9255-d5ac27fde532.png)

**If possible**
 - NodeJS version: 16
 - Bot version: latest

**Additional context**

**Comment by LoopyChimp** [comment]
Hello!

Can you send me a screenshot of your developer portal in oath2 please! 

Thanks!

**Comment by knifeworm** [comment]
Here u go 
![image](https://user-images.githubusercontent.com/77696553/136688352-f0f8404b-ad25-455f-a327-54ffc721e312.png)

**Comment by LoopyChimp** [comment]
Hello,
After looking at your developer portal, are you hosting on your pc?

**Comment by knifeworm** [comment]
Yes

**Comment by saiteja-madha** [comment]
Add this and it should work
```
http://localhost:8080/api/callback
```

**Comment by knifeworm** [comment]
Same error

**Comment by LoopyChimp** [comment]
Can you send a ss of your config file with the dashboard info please

**Comment by knifeworm** [comment]
Here u go 
![image](https://user-images.githubusercontent.com/77696553/136688544-f415215c-0161-44fd-8cb2-0e5c4407d12b.png)

**Comment by LoopyChimp** [comment]
put /api/callback on the dashboard not in the config file

**Comment by knifeworm** [comment]
Ok done that and it works but now i get the error [2021-10-10 09:32:12:651] [error] Unhandled exception : TypeError: fetch is not a function

**Comment by LoopyChimp** [comment]
Does it point out where the error is?? if so can you screenshot the code for us!

**Comment by saiteja-madha** [comment]
Hop into our support discord.
https://discord.gg/fE75UShbqB
