### ISSUE TITLE
USER_BANNER_NOT_FETCHED Error

### ISSUE THREAD

**Issue by kegri** [saiteja-madha/discord-js-bot#40]
**Describe the bug**
Error when login into dashboard

**To Reproduce**
Login to the dashboard on localhost

**If possible**
 - NodeJS version: v16.11.0
 - Bot version: 3.3.1

**Comment by saiteja-madha** [comment]
Hey, this issue was just identified
Please make change in this line
https://github.com/saiteja-madha/discord-js-bot/blob/21b4f0be3064364120ac8aa08fd1fa8a316eef02/dashboard/utils.js#L43

Remove
```
toJSON()
```

**Comment by saiteja-madha** [comment]
If you need help with anything else, feel free to join us at
https://discord.gg/fE75UShbqB
