### ISSUE TITLE
Cant use the dashboard. 

### ISSUE THREAD

**Issue by DFanso** [saiteja-madha/discord-js-bot#409]
when i go to the local url and allow the auth it will not redirrect back the the dashboard and giving this error in logs , ``{"level":20,"time":1691558048944,"pid":24592,"hostname":"MSI","error":"invalid_client"}
{"level":50,"time":1691558048944,"pid":24592,"hostname":"MSI","msg":"Failed to login to dashboard! Check /logs folder for more details"}``

 - NodeJS version: LTS
 - Bot version: LTS

Screenshot: https://cdn.discordapp.com/attachments/1136206243543920660/1138700402062282762/image.png

**Comment by rhaym-tech** [comment]
This is not a bug, it's because you didn't setup `BOT_SECRET` and `SESSION_PASSWORD` properly in `.env`
And since your issue has been fixed in Support Server you should close this issue

**Comment by DFanso** [comment]
yeah sorry my bad
