### ISSUE TITLE
Local Node Issue

### ISSUE THREAD

**Issue by EternalBlissed** [saiteja-madha/discord-js-bot#413]
ERROR: Node "Local Node" encountered an error: Error: connect ECONNREFUSED ::1:2333.: Error: connect ECONNREFUSED ::1:2333
 
 How to fix?

**Comment by rhaym-tech** [comment]
1. this is not a bug, you're stupid enough to realize that you didn't change default lavalink values
2. you're asking for support, which should be provided in support server not here
https://discord.gg/h2H9Urep

and by the way this is a lavalink you should use, replace it in config.js => MUSIC
```js
{
  host: "lavalink.infinity-bot.live",
  port: 19212,
  password: "infinity_lavalink",
  id: "Infinity Lavalink",
  retryDelay: 5000,
  secure: false,
}
```
