### ISSUE TITLE
Bug With Pokemon Command

### ISSUE THREAD

**Issue by Nocturnal-Compiler** [saiteja-madha/discord-js-bot#42]
**Describe the bug**
  ###pokedex command aint workin it says for any pokemon "pokemon not found"

**To Reproduce**
use pokedex command

**Expected behavior**
you should get a error in you terminal/console

**Screenshots**

**Comment by LoopyChimp** [comment]
Hey! Sorry for the late reply! Let me check this out and ill get back to you

**Comment by LoopyChimp** [comment]
Hey! I managed to get this myself. Let me attempt to work on a fix for this!
