### ISSUE TITLE
Music Dosnt want to play 

### ISSUE THREAD

**Issue by PvpGods** [saiteja-madha/discord-js-bot#421]
**Describe the bug**
A clear and concise description of what the bug is. ( The bot finds the Music but it keeps on disconnecting after joining the channel then it says Quaue ended idk why but it worked perfectly fine yesterday now it dosnt work again

**To Reproduce**
Steps to reproduce the behavior: it will disconnect right after trying to play the song and it leaves and Quaue ends

**Expected behavior**
A clear and concise description of what you expected to happen. It suppose to just play the music but it isn't 

**Screenshots**

**If possible**
 - NodeJS version: 18
 - Bot version: I forgot I just updated it

**Additional context**

Really annoying has been looking tru things to find why but no errors comes it just leaves 
![Screenshot_20230830_065449_Discord](https://github.com/saiteja-madha/discord-js-bot/assets/89556734/146aac00-fa2c-413b-83df-2886cba2a1ea)

**Comment by rhaym-tech** [comment]
This bug is caused by Lavalink because you're using a youtube url
Lavalink/Lavaplayer recently is getting 403 error from youtube
See [YouTube 403 not success #897](https://github.com/lavalink-devs/Lavalink/issues/897)

**Comment by PvpGods** [comment]
I don't get any errors it just disconnects

**Comment by PvpGods** [comment]
Thanks

**Comment by PvpGods** [comment]
Resolved

**Comment by rhaym-tech** [comment]
Yeah you won't get errors in your bot logs but you'll get errors in your Lavalink console
