### ISSUE TITLE
Dashboard looping

### ISSUE THREAD

**Issue by MrTabaOfficial** [saiteja-madha/discord-js-bot#422]
hi i have That problem "error":"invalid_client" While Authorization i m looping in discord Authorization

**Comment by imnaiyar** [comment]
Make sure you have correctly placed the dashboard url in config.js, without `/` in the last. And on your discord dev portal, you have put redirect url as `yourURL/api/callback`
And in .env, you've put client secret id

**Comment by MrTabaOfficial** [comment]
I did

**Comment by MrTabaOfficial** [comment]
So now i uploaded on server and after Identify There is nothing just saying This site can’t be reached

**Comment by imnaiyar** [comment]
Make sure how correctly placed the dashboard url in config.js, without `/` in the last. And on your discord dev portal, you have put redirect url as `yourURL/api/callback`
And in .env, you've put client secret id

**Comment by imnaiyar** [comment]
> So now i uploaded on server and after Identify There is nothing just saying This site can’t be reached

Show me your config.js and your dev portal url

**Comment by MrTabaOfficial** [comment]
![image](https://github.com/saiteja-madha/discord-js-bot/assets/121251795/201821a3-d211-4aa3-866b-3d87d0477188)

**Comment by MrTabaOfficial** [comment]
![image](https://github.com/saiteja-madha/discord-js-bot/assets/121251795/5c9acfdf-0aed-428c-84c2-00250834093a)

**Comment by MrTabaOfficial** [comment]
what do u think ?

**Comment by imnaiyar** [comment]
Does your hosting provide `https`?
Make sure its `http` and not `https`

**Comment by MrTabaOfficial** [comment]
wait that was https now http  let me try

**Comment by MrTabaOfficial** [comment]
i Loged in Dashboard but Server is not visable there

**Comment by rhaym-tech** [comment]
It only shows servers that you're an admin in, also you have to close this issue since your problem has been fixed

**Comment by iamvikshan** [comment]
Also i wrote a lil guide on dashboard if you ever feel lost again check it [here](https://docs.vikshan.me/installation/dashboard)
