### ISSUE TITLE
Sub Commands dont show in "/help" command

### ISSUE THREAD

**Issue by MohamedShadd** [saiteja-madha/discord-js-bot#427]
**Describe the bug**
Sub commands are supposed to be shown under the **Description** subtitle.
<img width="285" alt="image" src="https://github.com/saiteja-madha/discord-js-bot/assets/110860909/7ab41fd1-2fba-404f-96ba-a5a7ce8f2344">

<img width="593" alt="image" src="https://github.com/saiteja-madha/discord-js-bot/assets/110860909/3c1f375b-886d-4401-b9e2-01c555554cc4">

**Screenshots**
<img width="285" alt="image" src="https://github.com/saiteja-madha/discord-js-bot/assets/110860909/1c96cd49-1093-444e-ab78-b49577e18723">

**Comment by saiteja-madha** [comment]
This will be fixed in #425 as part of 5.5.0 release
