### ISSUE TITLE
Dashboard redirecting to Authorize Page

### ISSUE THREAD

**Issue by taynotfound** [saiteja-madha/discord-js-bot#43]
**Describe the bug**
As the Title says. When Authorizing it just straight up redirects to the authorize Page

**To Reproduce**
1. Run on Localhost
2. Try to Authorize

**Expected behavior**
Should authorize

**Screenshots**
https://cdn.discordapp.com/attachments/810874693136809995/898593304931880980/2021-10-15_17-28-27.mkv

**If possible**
 - NodeJS version: 16.11.1
 - Bot version: Newest from Source

**Comment by saiteja-madha** [comment]
What is the dashboard baseUrl in `config.js`?

You may join [support discord](https://discord.gg/fE75UShbqB)

**Comment by taynotfound** [comment]
Localhost:8080/

**Comment by saiteja-madha** [comment]
> Localhost:8080/

Can you show me your `config.json`
Also what have to added in the discord developers portal
