### ISSUE TITLE
Music commands don't work

### ISSUE THREAD

**Issue by Glerik23** [saiteja-madha/discord-js-bot#432]
![image](https://github.com/saiteja-madha/discord-js-bot/assets/99348800/3b77b4fc-8f65-4e53-8382-0bace3a72aa7)
![image](https://github.com/saiteja-madha/discord-js-bot/assets/99348800/6f5e5f85-5121-4cde-8fbb-a8706e34e4a6)

how can I fix it?

**Comment by rhaym-tech** [comment]
This is bugs report section and not for support
Your problem is related to your Lavalink, bot works fine, next time ask in support server

**Comment by Glerik23** [comment]
@rhaym-tech Okay, thx

**Comment by rhaym-tech** [comment]
Close the issue since you done

**Comment by SmYt-INDIA** [comment]
Please Change The Lavalink And Change The Source
