### ISSUE TITLE
Dashboard Not Working

### ISSUE THREAD

**Issue by Nightro-Fx** [saiteja-madha/discord-js-bot#433]
What am I doing wrong here?

![image](https://github.com/saiteja-madha/discord-js-bot/assets/79646876/270997de-7c0e-4dff-88fd-68a3a80e2530)
![image](https://github.com/saiteja-madha/discord-js-bot/assets/79646876/09f56230-df9c-4462-b2c9-1b6e99f1b7de)
![image](https://github.com/saiteja-madha/discord-js-bot/assets/79646876/b74b9b7a-8185-414f-bd63-eb660455096d)

**Comment by prosilentgamer2** [comment]
This is not a bug. You also where helped in the discord.

**Comment by Nightro-Fx** [comment]
Wdym?

**Comment by prosilentgamer2** [comment]
This is not a bug.
