### ISSUE TITLE
I need some help here

### ISSUE THREAD

**Issue by MrTabaOfficial** [saiteja-madha/discord-js-bot#436]
How to migrate db v4 to v5 ? there is script so how can i acitvate it

**Comment by iamvikshan** [comment]
@MrTabaOfficial , did you get assistance? I f not;
- [ ] add this line to your package.json under scripts, you can reference my [package.json](https://github.com/vixshan/mochi/blob/e94d5006dfffd6c3ce751eaf3bcddc71e58a6080/package.json#L17)
```json
    "migrate-db": "node ./scripts/db-v4-to-v5.js"
``` 
- [ ] run the following command;
```bash
npm run migrate-db
```
- [ ] You should be good to go now! If this resolved your issue, please consider starring my project, happy coding!

**Comment by MrTabaOfficial** [comment]
> @MrTabaOfficial , did you get assistance? I f not;
> 
> * [ ]  add this line to your package.json under scripts, you can reference my [package.json](https://github.com/vixshan/mochi/blob/e94d5006dfffd6c3ce751eaf3bcddc71e58a6080/package.json#L17)
> 
> ```json
>     "migrate-db": "node ./scripts/db-v4-to-v5.js"
> ```
> 
> * [ ]  run the following command;
> 
> ```shell
> npm run migrate-db
> ```
> 
> * [ ]  You should be good to go now! If this resolved your issue, please consider starring my project, happy coding!

I added 2 command Line in Bot.js at once. you cant run script single it need more thing so you must add in main run file

**Comment by iamvikshan** [comment]
> > @MrTabaOfficial , did you get assistance? I f not;
> > 
> > * [ ]   add this line to your package.json under scripts, you can reference my [package.json](https://github.com/vixshan/mochi/blob/e94d5006dfffd6c3ce751eaf3bcddc71e58a6080/package.json#L17)
> > 
> > ```json
> >     "migrate-db": "node ./scripts/db-v4-to-v5.js"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * [ ]   run the following command;
> > 
> > ```shell
> > npm run migrate-db
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * [ ]   You should be good to go now! If this resolved your issue, please consider starring my project, happy coding!
> 
> I added 2 command Line in Bot.js at once. you cant run script single it need more thing so you must add in main run file

Actually I did as i mentioned earlier and voila, it worked, but thanks now i know a new approach i can use, cheers
