### ISSUE TITLE
Mongoose error

### ISSUE THREAD

**Issue by theosanct0s** [saiteja-madha/discord-js-bot#44]
when I add the bot on a server, it doesn't respond to commands and gives this error on the console:

mongoError: E11000 duplicate key error collection: test.guilds index: id_1 dup key: { id: null }

**Comment by saiteja-madha** [comment]
It seems like you have manually edited something in mongodb guilds collection. Check _id field if it's duplicated

**Comment by theosanct0s** [comment]
How can I do this?

**Comment by saiteja-madha** [comment]
Did you manually modify anything in the database?

**Comment by theosanct0s** [comment]
I dont know

**Comment by Adenyyy** [comment]
Hello, we cannot help you if we do not know what you changed. Please let us know the appropriate information so we can do our best to help.

**Comment by theosanct0s** [comment]
how do i know if i moved something manually?

**Comment by saiteja-madha** [comment]
> how do i know if i moved something manually?

Try to create a fresh mongoose database and check it still the error occurred

**Comment by theosanct0s** [comment]
the problem was in the old database, I made a new one and it worked! thanks
