### ISSUE TITLE
Where is command permsission handled?

### ISSUE THREAD

**Issue by 0x32-l3git** [saiteja-madha/discord-js-bot#448]
I am trying to add an override so the owner IDs (config.js) can do any moderator feature without permissions.
I have tried to edit ModUtils.js with no avail.
```javascript
const memberInteract = (issuer, target) => {
  if (MODERATION.OWNER_IDS.includes(issuer.id)) return true;
  const { guild } = issuer;
  if (guild.ownerId === issuer.id) return true;
  if (guild.ownerId === target.id) return false;
  return issuer.roles.highest.position > target.roles.highest.position;
};
```

**Comment by saiteja-madha** [comment]
Command permissions and validations are done here: https://github.com/saiteja-madha/discord-js-bot/blob/main/src/handlers/command.js#L15

**Comment by zephr1213** [comment]
I didn't see the response. Just got an email it was closed. I will take a look.
