### ISSUE TITLE
Owner commands

### ISSUE THREAD

**Issue by LoopyChimp** [saiteja-madha/discord-js-bot#45]
You should make owner commands so only the people who use it can see it which should only be the owners so use ephemeral, i can assist if you need it, i have made a few changes to it on my version on my pc.

**Comment by saiteja-madha** [comment]
This will be added in v4 release

**Comment by LoopyChimp** [comment]
So your using Ephermal? So only bot owner sees it??? I looked but saw no reference to Ephermal
