### ISSUE TITLE
Dashboard not working

### ISSUE THREAD

**Issue by CPS7** [saiteja-madha/discord-js-bot#451]
**Dashboard not Working**
Client don't support /api/callback

**Screenshots**
![Screenshot_20231121_234224_Chrome](https://github.com/saiteja-madha/discord-js-bot/assets/149692687/d20d8c81-1a91-4780-bcf4-b9f8569ab788)

**If possible**
 - NodeJS version:19

**Additional context**
Please help

**Comment by rhaym-tech** [comment]
Issues section is made for reporting Bot bugs and issues not asking for support
For support join support server:
https://discord.gg/uE6BqG66
