### ISSUE TITLE
TypeError [ColorConvert] - handleTicketOpen

### ISSUE THREAD

**Issue by NNKTV28** [saiteja-madha/discord-js-bot#453]
**Describe the bug**

The issue is because in the config.js in the bots root folder the ticket is wrong
```JS
TICKET: {
    ENABLED: true,
    CREATE_EMBED: "##43B581",
    CLOSE_EMBED: "#F04747",
  },
```
it should be like this:
```JS
TICKET: {
    ENABLED: true,
    CREATE_EMBED: "#43B581", // there was an extra #
    CLOSE_EMBED: "#F04747",
  },
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**If possible**
 - NodeJS version:
 - Bot version:

**Additional context**

**Comment by rhaym-tech** [comment]
Bruh this is not our issue, you clearly imported the code from an unofficial source or you edited it by mistake.
Original code shows that everything is fine:
https://github.com/saiteja-madha/discord-js-bot/blob/main/config.js

**Comment by NNKTV28** [comment]
whoops
