### ISSUE TITLE
ERROR: Unhandled exception: Used disallowed intents

### ISSUE THREAD

**Issue by moibg** [saiteja-madha/discord-js-bot#455]
I want to know to fix it plz !

**Comment by ghost** [comment]
same as before
got to the [developer portal](https://discord.com/developers/applications) click on ur bot and scroll a bit down click all the 3 sliders until they look like this:

![image](https://github.com/saiteja-madha/discord-js-bot/assets/122749762/7addf142-63fc-4a11-9f1a-a1f095cea4a9)
now retry and it should work!
LG
StrangeAPI
