### ISSUE TITLE
Dashboard doesn't work.

### ISSUE THREAD

**Issue by ANIKETEDITZ** [saiteja-madha/discord-js-bot#459]
**Describe the bug**
When I try to open dashboard of the bot, it returns with Invalid Redirect Uri 
(Using Replit)(Bot secret is correct)

**To Reproduce**
Proper discord auth page 

**Expected behavior**
This shouldn't happen

**Screenshots**

![Screenshot_2024-01-02-18-58-14-23_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/saiteja-madha/discord-js-bot/assets/75073704/9291d870-aaae-4be9-86e3-ac53ae059d4a)
![Screenshot_2024-01-02-18-59-01-00_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/saiteja-madha/discord-js-bot/assets/75073704/98cfed74-fb14-4a85-af93-d9574cbfe24b)

**If possible**
 - NodeJS version: 10.2.5
 - Bot version: idk, but I forked it 3 days ago

**Additional context**
I tried to ask for support in server but no one could help with it.

**Comment by prosilentgamer2** [comment]
Your issue is using replit. Thats not a host at all.

**Comment by ANIKETEDITZ** [comment]
Ok
