### ISSUE TITLE
how to self host the image API

### ISSUE THREAD

**Issue by BallisticOK** [saiteja-madha/discord-js-bot#460]
Hey there,

I'm just reaching out to ask how to self-host that image API, as the URL no longer seems to be working or if there is a new URL that I am not aware of. Thanks!

**Comment by rhaym-tech** [comment]
Strange API is closed source and it's not possible to be self-hosted,
Also the API has been moved to:
https://strangeapi.hostz.me/

**Comment by saiteja-madha** [comment]
This is now public: https://github.com/strange-bot/strange-image-api
