### ISSUE TITLE
Recording command!

### ISSUE THREAD

**Issue by halvi07** [saiteja-madha/discord-js-bot#466]
Make a command for recording a voice channel. Make The clips avalible through the dashboard

**Comment by armoredeagle69** [comment]
Well my friend, that is what we developers like to call illegal and against the Discord TOS. You can not record a voice channel without consent from all users in the channel. Once you have received consent from all users in the channel, then you can refer to [joining a voice channel](https://discordjs.guide/voice/voice-connections.html#creation) and also looking into the [node fs documentation](https://nodejs.org/api/fs.html), specifically [fs.createWriteStream](https://nodejs.org/api/fs.html#fscreatewritestreampath-options). You will also need [Prism Media](https://www.npmjs.com/package/prism-media) for the opus decoder. As for anything past what I have mentioned here, the rest is on you. Also, please use the Discord server for questions regarding this, not a bug report issue.
