### ISSUE TITLE
Token Error

### ISSUE THREAD

**Issue by ogxxxxxxxgood** [saiteja-madha/discord-js-bot#492]
I entered the current in this file, but I get an error:

[2024-03-08 04:03:43] INFO: Validating config file and environment variables
[2024-03-08 04:03:43] ERROR: env: BOT_TOKEN cannot be empty
![image](https://github.com/saiteja-madha/discord-js-bot/assets/162664295/80bf3de1-e9b9-4c04-b989-6f5902d47ade)

**Comment by imnaiyar** [comment]
This is for the issues in the bot source. Not skill issue. Please read the guide on how to set up the bot

**Comment by Numdiggg** [comment]
Did you change the .env.example to.env? if no do it
