### ISSUE TITLE
Bot invite command

### ISSUE THREAD

**Issue by BryanAlberts** [saiteja-madha/discord-js-bot#498]
![image](https://github.com/saiteja-madha/discord-js-bot/assets/59321692/4b6a00d8-cd9a-4512-9351-1ab107767af0)

![image](https://github.com/saiteja-madha/discord-js-bot/assets/59321692/6b4ac2e7-4013-47e2-bc1d-dbfae24d5bdf)

i got error while using bot invite command

**Comment by BryanAlberts** [comment]
nvm i solved

**Comment by maralexofficial** [comment]
Hey. How you have solved this problem?
