### ISSUE TITLE
Dashboard custom url without replit!

### ISSUE THREAD

**Issue by LoopyChimp** [saiteja-madha/discord-js-bot#5]
Hey! Me again, I forgot to ask last time how do I make it so that I can use a custom url without replit as replit struggles with v16 of node rn and won't forever upgrade which is bad when I'm away!

**Comment by saiteja-madha** [comment]
> Hey! Me again, I forgot to ask last time how do I make it so that I can use a custom url without replit as replit struggles with v16 of node rn and won't forever upgrade which is bad when I'm away!

Dashboard is taken from Atlanta Bot and it has a pretty neat guide for installation steps. Here you go: https://github.com/Androz2091/AtlantaBot/discussions/371

**Comment by saiteja-madha** [comment]
Feel free to join us at [discord](https://discord.gg/tGkbpCD)

**Comment by LoopyChimp** [comment]
> Feel free to join us at [discord](https://discord.gg/tGkbpCD)

I just joined it thanks for that!

**Comment by LoopyChimp** [comment]
> > Hey! Me again, I forgot to ask last time how do I make it so that I can use a custom url without replit as replit struggles with v16 of node rn and won't forever upgrade which is bad when I'm away!
> 
> Dashboard is taken from Atlanta Bot and it has a pretty neat guide for installation steps. Here you go: [Androz2091/AtlantaBot#371](https://github.com/Androz2091/AtlantaBot/discussions/371)

Checking it out now!
thanks for this
