### ISSUE TITLE
Embed command (/embed) 

### ISSUE THREAD

**Issue by Paranthaman-06** [saiteja-madha/discord-js-bot#503]
![Screenshot_2024-03-25-18-33-33-387_com discord](https://github.com/saiteja-madha/discord-js-bot/assets/118628608/0802b0a8-635a-46a6-83da-39b9a8ff1256)

If I were use /embed bot command there
Is a problem where I can't insert thumbnail photo
Please fix this

**Comment by imnaiyar** [comment]
Modals only support upto five text inputs, so cant add another for the thumbnail, you may need to modify it yourself to get that another way (like how you add fields later)

**Comment by Paranthaman-06** [comment]
Can you add that in next update please
Add thumbnail like you said

**Comment by imnaiyar** [comment]
Join the support server and submit a suggestion there

**Comment by saiteja-madha** [comment]
Duplicate request #483
