### ISSUE TITLE
Dashboard not working

### ISSUE THREAD

**Issue by TheGrayFox-code** [saiteja-madha/discord-js-bot#517]
Hey...
i dont know if this is a bug, so i opned a blank issue.

when i set the dashboard up like in the documentation i get this error... (by the way... this mean "invalid OAuth2 redirect_uri")
![image](https://github.com/saiteja-madha/discord-js-bot/assets/157584320/21ce376e-a22d-4b49-bff9-17474d926c80)

**Comment by SoundDr0ut** [comment]
Join the support server and submit a suggestion there

**Comment by PUSHKAR2521** [comment]
Bro you have to add your dashboard url in your Discord Developer Bot Redirects
& If you are running your bot from Local Device than add : http://localhost:{PORT}
In Port change value according Config.js
![Capture](https://github.com/saiteja-madha/discord-js-bot/assets/117440896/2d044835-2c85-4c59-9831-e2a1ca723b07)

**Comment by saiteja-madha** [comment]
Follow the steps in the docs and it should work. Alternatively, feel free to join our Discord server.
