### ISSUE TITLE
Documentation URL

### ISSUE THREAD

**Issue by JoshuaBilboe96** [saiteja-madha/discord-js-bot#528]
https://strangedocs.hostz.me/ is not loading for the Documentation

**Comment by ZwergTuete** [comment]
Yes, the CNAME User is cross banned... but idk what that means. Can some1 fix that?

**Comment by chethanyadav456** [comment]
@saiteja-madha ig u misconfigured the cloudflare settings, do fix it.

**Comment by saiteja-madha** [comment]
Done. It should be up now 🆙
