### ISSUE TITLE
Getting disconnected randomly while playing track

### ISSUE THREAD

**Issue by NoobingPro** [saiteja-madha/discord-js-bot#61]
I tried the bot and it works completely fine but sometimes it get disconnected from VC randomly and logs an error.  I have filed the .env and config.json file completely but still it gets disconnected. 
All dependencies are correctly installed and running with node 16.x .
Its not the host problem as i tried deploying it at many vps

**Comment by saiteja-madha** [comment]
> I tried the bot and it works completely fine but sometimes it get disconnected from VC randomly and logs an error. I have filed the .env and config.json file completely but still it gets disconnected. All dependencies are correctly installed and running with node 16.x . Its not the host problem as i tried deploying it at many vps

Please share the complete error details from `logs/` directory

**Comment by NoobingPro** [comment]
14:13:57.994 INFO  Node "DBL Lavalink" connected 
14:51:36.092 ERROR Track Error Something broke when playing the track. 
14:51:36.092 DEBUG [883932452425457664] Track Error 
14:52:32.508 ERROR Track Error Something broke when playing the track. 
14:52:32.509 DEBUG [852187729474617384] Track Error 
14:52:47.706 ERROR Track Error Something broke when playing the track. 
14:52:47.707 DEBUG [852187729474617384] Track Error

**Comment by saiteja-madha** [comment]
This is an error linked with erela.js
We are moving to other music library soon and hopefully this will be fixed
