### ISSUE TITLE
Mongo E11000 error

### ISSUE THREAD

**Issue by CherryWaffle** [saiteja-madha/discord-js-bot#76]
` 'MongoError:' E11000 duplicate key error collection: test.guilds index: guildId_1 dup key: { guildId: null }`

**If possible**
 - NodeJS version: 16.11.1
 - Bot version: 4.0.1

**Additional context**
I have changed mongoURI, bot token, but still it wont work

**Comment by saiteja-madha** [comment]
> ` 'MongoError:' E11000 duplicate key error collection: test.guilds index: guildId_1 dup key: { guildId: null }`
> 
> **If possible**
> 
> * NodeJS version: 16.11.1
> * Bot version: 4.0.1
> 
> **Additional context** I have changed mongoURI, bot token, but still it wont work

I could not replicate this error.
Did you do something specific?

**Comment by CherryWaffle** [comment]
Nope, I just restarted the bot once, and this pops up. I'l re-clone nd try again.

**Comment by CherryWaffle** [comment]
![image](https://user-images.githubusercontent.com/72537594/148682621-f73db6ec-b103-4163-87ee-83476b7f11b1.png)

Same Error

**Comment by saiteja-madha** [comment]
> ![image](https://user-images.githubusercontent.com/72537594/148682621-f73db6ec-b103-4163-87ee-83476b7f11b1.png)
> 
> Same Error

Maybe guildId is being passed null somewhere.

`
https://github.com/saiteja-madha/discord-js-bot/blob/c190e8e0158b463bddbd71f27711ae49d2b3fe73/src/schemas/Guild.js#L139 
`
Add a small code snippet here to raise an error if guildId is null
```
if (!guild.id) {
   throw new Error("Guild ID is null");
}
```

**Comment by saiteja-madha** [comment]
You may join our discord to investigate this further: https://discord.gg/fE75UShbqB

**Comment by CherryWaffle** [comment]
![image](https://user-images.githubusercontent.com/72537594/148684114-5915b9ab-e21d-4de7-899f-6186c4063782.png)

**Comment by CherryWaffle** [comment]
I figured out the problem @saiteja-madha . The mongoURI can be used only once (per bot). If we try to use the same mongoURI on the same code again (this time a different fork) it won't work, and it throws this error.
