### ISSUE TITLE
Discord Status Issue in Dashboard

### ISSUE THREAD

**Issue by nostorian** [saiteja-madha/discord-js-bot#77]
**Describe the bug**
Whether your status is set to dnd, online or idle ; the dashboard will show the offline status only.

**To Reproduce**
This happens when you launch your bot dashboard and sign in from your discord account.

**Expected behavior**
If the user's status is set to dnd, online, idle or offline ; it should show that status only in the dashboard and not just show offline status regardless of what your status is set to in discord.

**Additional Info**
 - NodeJS version: 16.13.1

**Comment by bunnydevx** [comment]
This is due to your bot not having the correct intents on!
