### ISSUE TITLE
Music System Bug

### ISSUE THREAD

**Issue by Nocturnal-Compiler** [saiteja-madha/discord-js-bot#78]
**Describe the bug**
While Playing A Song It Should Be Like Only We/Song Requesters Can Access The /stop /skip etc... commands But Any One Can Access /stop /skip Commands Please Change It So That Only Admins can use those commands while a track  is being played. ty

**To Reproduce**
try /play (song of your choice) next log into your alt account and try /stop

**Comment by saiteja-madha** [comment]
This isn't a bug and is planned feature. Anyone in the music room can access the music commands.
This implementation may be changed in future releases
